### ISSUE TITLE
Error at multiple measured points in a polygon- Leica TS07

### ISSUE THREAD

**Issue by DeMelkor** [gbv/Tachy2GIS#7]
`KeyError: '9' 
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\tachyconnect\ts_control.py", line 181, in register_reply
    request = self.slots.pop(message_id)
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Tachy2GIS-main_3_2x\Tachy2GIS.py", line 237, in vertex_received
    new_vtx = make_vertex(line)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\tachyconnect\GSI_Parser.py", line 405, in make_vertex
    vtx_data = parse(line)[0]
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\tachyconnect\GSI_Parser.py", line 383, in parse
    units[label] = dict_units_attributes_digits[unitInfo]
KeyError: '9'

Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-Version: 3.24.2-Tisler Tisler, 13c1a028

**Comment by Landesamt-fuer-Archaeologie-Sachsen** [comment]
This error is caused by GSI_parser.py in tachyconnect. Every 10th measurement with a TS07, the GSI data sent by the total station cannot be interpreted due to a change in the unit information. A simple way to avoid this (which does not solve the problem, but works for the moment) would be to suppress the execution of line 383 in parser.py, as we do not need the unit information so far.
